
```{r setup, include=FALSE}
knitr::opts_chunk$set(include = FALSE, echo = FALSE, warning = FALSE, message = FALSE)
```


```{r}
library(tidyverse) # data manipulation
library(tidytuesdayR) # to pull in data
library(reactable) # to make table
library(htmltools) # for html components
library(reactablefmtr) # easier implementation of reactable
library(teamcolors) # for logos
library(janitor) 
library(crosstalk) # for slider and school search interactivity

```


```{r, cache=TRUE}
# pulling in data ---------------------------------------------------------

tidy_year <- 2020
tidy_week <- 41

tuesdata <- tt_load(tidy_year, week = tidy_week)

# logos
df_teamcolors <- teamcolors %>% 
  filter(league == "ncaa") %>% 
  select(division, location, logo, division) %>% 
  # need to mutate to allow for left_join with df_tournament below, still missing logos for a few teams, notably UConn
  mutate(location = str_replace_all(location, "State", "St."))

df_tournament <- tuesdata$tournament %>% 
  left_join(df_teamcolors, by = c("school" = "location")) %>% 
  # if missing logo, replace with NCAA logo
  mutate(logo = if_else(is.na(logo), "https://upload.wikimedia.org/wikipedia/commons/d/dd/NCAA_logo.svg", logo
  ))

# lookup table for seed points
seed_point_table <- 
  tribble(
    ~seed, ~points,
    1, 	  100,
    2, 	  72.7,
    3, 	  54.5,
    4,	  48.5,
    5,	  33.3,
    6,	  33.3,
    7,	  27.3,
    8,	  21.2,
    9,	  18.2,
    10,	  18.2,
    11,	  18.2,
    12,	  15.2,
    13,	  9.09,
    14,	  6.06,
    15,	  3.03,
    16,	  0
  )

```

```{r}

# wrangling ---------------------------------------------------------------

# dataset starts in 1982 and ends in 2018 so not quite 4 decades.  
sample_years <- df_tournament %>% 
  distinct(year) %>% 
  count() %>% 
  pull(n)

# adding in trophy emoji for first place
df_trophy_emoji <- df_tournament %>% 
  mutate(
    champs = case_when(
    tourney_finish == "Champ" ~ as.character(emo::ji("trophy")),
    TRUE ~ "")
    ) %>% 
  group_by(school) %>% 
  mutate(total_champs = glue::glue_collapse(champs)) %>% 
  ungroup() %>% 
  distinct(school, .keep_all = TRUE) 

# seed points by decade

df_seed_pts <- df_tournament %>% 
  left_join(seed_point_table, by = "seed") %>% 
  mutate(decade = floor(year / 10) * 10) %>%  
  group_by(school, decade) %>% 
  summarise(total_decade_pts = sum(points)) %>% 
  ungroup() %>% 
  group_by(school) %>% 
  mutate(total_overall = sum(total_decade_pts) / sample_years) %>% 
  ungroup() %>% 
  mutate(decade_avg = case_when(
    decade < 1990 ~ total_decade_pts / 8,
    decade > 2009 ~ total_decade_pts / 9,
    TRUE ~ total_decade_pts / 10)
    ) %>% 
  select(-total_decade_pts)

 # Input for Main table  ---------------------------------
df_all_teams <- df_seed_pts %>%
  pivot_wider(names_from = decade,  
              values_from = decade_avg) %>% 
  mutate(
    across(
      .cols = is.numeric,
      .fns = ~round(replace_na(., 0), 0)
        )
      ) %>% 
  arrange(desc(total_overall)) %>% 
  left_join(df_trophy_emoji) %>% 
  mutate(total_champs = if_else(total_champs == "", 
                                "\u2718", 
                                as.character(total_champs))) %>% 
  select(logo, school, total_champs, "1980":"2000", "2010", total_overall) 

 # sub table ---------------------------------

df_seeds_totals <- df_tournament %>% 
  complete(school, nesting(year, seed)) %>% 
  mutate(tourney = if_else(is.na(reg_w), 0, 1)) %>% 
  count(seed, school, wt = tourney) %>% 
  drop_na() %>%
  pivot_wider(names_from = seed,
              values_from = n) %>% 
  adorn_totals("col") %>% 
  mutate(Seed = "Count")

df_seeds_perc <- df_seeds_totals %>%
  mutate(samp_years = sample_years,
         Seed = "%") %>% 
  mutate(
    across(
    .cols = is.numeric,
    .fns = ~ (. / samp_years * 100)
    )
  ) %>% 
  select(-samp_years)
    
df_seeds_comb <- bind_rows(df_seeds_totals, df_seeds_perc) %>% 
  adorn_rounding(digits = 0) 

df_seeds_comb_1_seed <- df_seeds_comb %>% 
  filter(Seed == "Count") %>% 
  select(school, '1')

 # Main table ---------------------------------
df_all_teams_seed <- df_all_teams %>% 
  left_join(df_seeds_comb_1_seed) %>% 
  rename(x1 = '1')

data_test <- SharedData$new(df_all_teams_seed)

```


```{r}
pal <- rcartocolor::carto_pal(n = 7, name = "Mint")

# for grouping
decades <- c('1980', '1990', '2000', '2010', 'total_overall')


tbl <- bscols(
  # creating slider and search bar interactivity
  widths = c(2, 10),
  list(
    filter_slider("1", "1 Seed Count", data_test, ~x1),
    filter_select("school", "School", data_test, ~school)
  ),
  reactable(data_test, details = function(index){
      # creating sub table
    df_seeds_react <- df_seeds_comb[df_seeds_comb$school == df_all_teams$school[index],] %>% 
      select(Seed, '1':'16', Total)
    htmltools::div(
      reactable(df_seeds_react,
                sortable = FALSE,
                defaultColDef = colDef(
                    minWidth = 25,
                    headerClass = "subheader"
                    ),
                  columns = list(
                    Total = colDef(
                      minWidth = 45
                      ),
                    Seed = colDef(
                      minWidth = 40,
                      align = "right"
                    )
                  )
        )
      )
      },
    # main table
    showSortIcon = FALSE,
    height = 650,
    width = 775,
    defaultColDef = colDef(
      style = reactablefmtr::color_scales(df_all_teams, pal),
      minWidth = 70,
      headerClass = "header"
    ),
    pagination = FALSE,
    showSortable = TRUE,
    theme = reactableTheme(
      headerStyle = list(
        "&:hover[aria-sort]" = list(background = "hsl(0, 0%, 96%)"),
        "&[aria-sort='ascending'], 
        &[aria-sort='descending']" = list(background = "hsl(0, 0%, 96%)"),
        borderWidth = "3px",
        align = "center"
        )
      ),
    columnGroups = list(
      colGroup(name = "Seed Points per Tournament", columns = decades) 
    ),
    columns = list(
      logo = colDef(
        name = "",
        sortable = FALSE,
        align = "right",
        width = 60,
        # adding logos; did this before I knew you could do this in {reactablefmtr}; see that package for easier implementation
        cell = function(value) {
            image <- img(src = value, height = "25px", width = "35px")
            tagList(
            div(style = list(display = "inline-block", width = "50px"), image)
            )
        }
      ),
      school = colDef(
        name = "School",
        align = "left",
        width = 100,
        class = "schoolfontsize"
      ),
      x1 = colDef(
        show = FALSE
      ),
      total_overall = colDef(
        html = TRUE,
        name = "<p>Overall<sup>1</sup></p>",
        class = "border-left"
      ),
      '1980' = colDef(
        name = "1980s",
        class = "fontsize",
        width = 60
      ),
      '1990' = colDef(
        name = "1990s",
        class = "fontsize",
        width = 70
      ),
      '2000' = colDef(
        name = "2000s",
        class = "fontsize",
        width = 70
      ),
      '2010' = colDef(
        name = "2010s",
        class = "fontsize",
        width = 70
      ),
      total_champs = colDef(
        name = "Championships",
        width = 200
      )
    )
  )
)

```


```{css, include = TRUE}
# additional styling

.subheader {
  border-bottom-color: #555;
}

.header {
  border-bottom-color: #555;
  font-size: 13px; 
}

.border-left {
  border-left: 4px solid #555;
  font-size: 13px;
  font-weight: 900;
}

.fontsize {
  font-size: 13px;
  font-weight: 900;
}

.schoolfontsize {
  font-size: 13px;
}

.body {
  font-size: 12px;
  font-family: "Fira Mono", Consolas, Monaco, monospace;
}

```


```{r, include = TRUE}
div(class = "body",
  div(
    tags$br(),
    tags$span(style = "font-weight:bold; font-size:30px", glue::glue("Imperial March ", emo::ji("basketball"))),
    tags$br(),
    tags$br(),
    "From 1982-2018 (37 seasons), the",
    tags$span(style = "color:#FF8200; font-weight:bold", "Tennesee Volunteers"),
    "and the",
    tags$span(style = "color:#000E2F; font-weight:bold", "UConn Huskies"),
    "won a combined 19 women's college basketball titles. As shown in the dropdowns,",
    tags$span(style = "color:#FF8200; font-weight:bold", "Tenneesee"), 
    "was awarded a #1 seed 22 times (or 60% of the time) over this period, while", 
    tags$span(style = "color:#000E2F; font-weight:bold", "UConn"), 
    "was awarded a #1 seed 21 times (or 57% of the time). Of 284 schools",
    tags$span(style = "color:#FF8200; font-weight:bold", "Tennessee"),
    "was the only school to appear in every tournament (37 appearances).  The next highest was the",
    tags$span(style = "color:#BA0C2F; font-weight:bold", "Georgia Bulldogs,"),
    "with 33 appearances. For further discussion on how seed points were derived, see footnote below and Neil Paine's",
    tags$a(style = "font-weight:bold", href="https://fivethirtyeight.com/features/louisiana-tech-was-the-uconn-of-the-80s/", target = "_blank", "FiveThirtyEight"),
    "article."
    ),
  tags$br(),
  
  tbl,
  
  tags$br(),
  div(style = "color: #999; font-weight: normal", HTML("<p><sup> 1</sup>Seed points award a score on a 100-point scale; a #1 seed gets 100 points, while the rest descend in proportion to the seed's expected wins during the tournament.</p>")),
  "TABLE: @schmid_07 | Adapted from:", 
  tags$a(href="https://fivethirtyeight.com/features/louisiana-tech-was-the-uconn-of-the-80s/", target = "_blank", "FiveThirtyEight"),
  emo::ji("fox"),
  "| Data: NCAA"
  )

```


