---
title: "2020/46 Phones"
author: "Bill Schmid"
date: "12/28/2020"
output: html_document
---
```{r setup, loading libraries}
knitr::opts_chunk$set(echo = TRUE)

library(tidytuesdayR)
library(tidyverse)
library(ggtext)
library(showtext)
library(rnaturalearth)
library(patchwork)
library(ggforce)
library(ggnewscale)

```


```{r setup, load data and fonts}

tidy_year <- 2020
tidy_week <- 46

tuesdata <- tt_load(tidy_year, week = tidy_week)

df_orig_mobile <- tuesdata$mobile
df_orig_landline <- tuesdata$landline

font_add_google(name = "Oswald", family = "Oswald")
showtext_auto()

options(scipen=999)

```

```{r wrangling}

fun_cagr <- function(n, val_1, val_2) {
  (val_2/val_1)^(1/n) - 1
}

df_mob_land <- df_orig_mobile %>% 
  select(code, year, mobile_subs) %>% 
  left_join(df_orig_landline, by = c("code", "year")) %>% 
  mutate(total_mob = mobile_subs * total_pop/100,
         total_land = landline_subs * total_pop/100,
         total_phones = total_mob + total_land,
         total_phones_per = landline_subs + mobile_subs,
         land_perc = total_land / total_phones)

df_mob_land_cagr_calc <- df_mob_land %>% 
  select(year, entity, total_phones, total_phones_per) %>% 
  group_by(entity) %>% 
  filter(year == 2017 | year == 1990) %>%
  # "any" function allows you to drop all factors levels (in this case, entity) based on conditional.  So if there is a valid value in one year for American Samoa but NA in another year for American Samoa, the filter will remove all instances of American Samoa.  Additional resource here: https://community.rstudio.com/t/delete-subgroups-conditionally/28105
  filter(!any(is.na(total_phones))) %>% 
  pivot_wider(names_from = year,
              values_from = c(total_phones, total_phones_per)) %>% 
  ungroup() %>% 
  drop_na() %>% 
  mutate(cagr_calc = fun_cagr(n = (2017-1990), 
                          val_1 = total_phones_1990, 
                          val_2 = total_phones_2017) * 100,
         cagr_calc = round(cagr_calc))  %>% 
  select(entity, cagr_calc) 

vec_fct_relevel <- df_mob_land %>%
  filter(year == 2017) %>% 
  slice_max(total_pop, n = 10) %>% 
  arrange(total_phones_per) %>% 
  pull(entity)

df_mob_land_share <- df_mob_land %>% 
  filter(entity %in% vec_fct_relevel) %>% 
  mutate(entity = factor(entity, levels = vec_fct_relevel),
         y = as.numeric(entity)) %>% 
  left_join(df_mob_land_cagr_calc) %>% 
  mutate(entity_text = glue::glue("<span style = 'font-size:50pt'>**{str_to_upper(entity)}**</span> <span style='font-size:20pt'> ({cagr_calc}%)</span>"),
         max_perc = max(total_phones_per[year == 2017], na.rm = TRUE)) 

df_ann_text <- df_mob_land_share %>% 
  group_by(entity) %>% 
  slice(1) %>% 
  ungroup()

sf_countries <- ne_countries(returnclass = "sf") %>% 
  select(name, geometry, continent) %>% 
  filter(!continent %in% c("Antarctica", "Oceania", "Seven seas (open ocean)")) %>% 
  mutate(top_10 = name %in% df_ann_text$entity)

```


```{r plot phone data}

theme_set(theme_void())

plot_phones <- ggplot(df_mob_land_share %>% 
                        group_by(entity) %>% 
                        filter(year == max(year) | year == min(year)) %>% 
                        ungroup(),
                      aes(x = year, y = y, group = entity)) + 
  geom_richtext(data = df_ann_text, aes(x = 2003,
                                     y = y + .3, 
                                     label = entity_text,
                                     label.color = NA),
                family = "Oswald",
                fill = "#F2DFCE") + 
  geom_link2(data = df_mob_land_share, 
            aes(x = year, y = y, size = land_perc, 
                alpha = land_perc, color = land_perc)) +
  scale_size(range = c(.1, 10)) +
  scale_color_gradient(low = "white", high = "black") +
  geom_point(size = 30, color = "black") +
  new_scale(new_aes = "size") +
  geom_point(aes(size = max_perc), color = "white") + 
  geom_point(aes(size = total_phones_per), color = "#02a9f7") +
  scale_size(range = c(1, 25)) + 
  scale_x_continuous(breaks = c(1990, 2017),
                     labels = c(1990, 2017)) +
  labs(x = NULL, y = NULL) + 
  theme_minimal(base_family = "Oswald") + 
  coord_cartesian(clip = "off") +
  annotate(
    "curve", x = 2006, xend = 2007,
    y = 10.4, yend = 10.7,
    curvature = .5,
    color = "grey18",
    size = 1) +
  geom_textbox(
    data = tibble(
      x = 2008,
      y = 10.8,
      label = "Total phone CAGR (1990-2017)"),
  aes(x = x, y = y, label = label),
  width = unit(3, "inch"),
  family = "Oswald",
  lineheight = 1.3,
  size = 5,
  fill = NA,
  box.colour = NA,
  inherit.aes = FALSE
) + 
  theme(panel.grid = element_blank(),
        axis.text.x = element_text(size = 40, face = "bold",
                                   margin = margin(t = 25)),
        axis.text.y = element_blank(),
        legend.position = "none",
        plot.margin = margin(t = 55, r = 45, b = 35, l = 15))

plot_world <- ggplot() +
  geom_sf(data = sf_countries, 
          aes(geometry = geometry, fill = top_10)) + 
  scale_fill_manual(values = c('#E8E8E8', '#02a9f7')) + 
  theme(legend.position = "none")
  
```


```{r plot text}

df_mob_land_count <- df_mob_land %>% 
  distinct(entity) %>% 
  count()

df_mob_land_per_cap <- df_mob_land_share %>% 
  filter(year == 1990 | year == 2017) %>% 
  group_by(year) %>% 
  filter(total_phones_per == max(total_phones_per, na.rm = T) |
           total_phones_per == min(total_phones_per, na.rm = T)) %>% 
  mutate(total_phones_per = round(total_phones_per))

plot_text <- ggplot() + geom_textbox(
  data = tibble(
    x = 0,
    y = c(.95, 0.8, .21),
    label = c(
      "<span style='font-size:55pt'>**Global Historical Phone Usage**</span>", 
      glue::glue("Using a dataset from **OurWorldInData.org**, the chart to the right shows the growth of total landline + mobile subscriptions and the relative decline of landlines versus mobile phones from 1990 to 2017. While the dataset included {df_mob_land_count$n[1]} countries, the data was filtered to only include the 10 most populous countries, highlighted in the map below."),
      "The <span style = 'font-size:25pt'>**black circles**</span> represent 2017 total phones per 100 people in **Japan**, which had the highest rate (184). This was sligthly above Russia, which had the second highest rate (179). 
      <br> <br>
      The <span style = 'font-size:25pt; color:#02a9f7'>**size of the dot**</span> corresponds to the total phones per 100 people in a given country and year. In 1990, **Bangladesh, Nigeria, India, China, Indonesia**, and **Pakistan** had minimal phone adoption rates, with fewer than 1 in 100 people having either a landline or mobile subscription. From 1990 to 2017, however, phone adoption rates exploded, with these same six countries having annual subscription growth rates above 20%. **Pakistan** exemplifies this rapid growth. While they had the lowest phone subscription rate (75) in 2017, they were well above the country with the highest phone subscription rate (56) in 1990, the **United States**.   
       <br> 
      The <span style = 'font-size:25pt'>**transparency and size of the lines**</span> represents the percentage of landlines and mobile phones among total phone subscriptions in a given country and year. The darker the line, the greater the percentage of landlines. **Russia, Nigeria, India**, and **Bangladesh** had no mobile phone subscriptions in 1990, but by 2017, the situation was almost entirely reversed, with several countries having nearly 100% mobile phone subscriptions."
      ),
    color = "black"
  ),
  aes(x = x, y = y, label = label, color = color),
  width = unit(8, "inch"),
  lineheight = 1.7,
  family = "Oswald",
  size = 7,
  fill = NA,
  box.colour = NA,
  hjust = 0
) +
  scale_color_identity() +
  coord_cartesian(clip = "off") +
  scale_x_continuous(limits = c(0, 1)) +
  scale_y_continuous(limits = c(0, 1)) + 
  labs(caption = "Data Viz: Bill Schmid @schmid_07") +
  theme(legend.position = "none",
        plot.caption = element_text(size = 16, hjust = .1))
  
```

```{r patch plots}
# seems to be a bug in patchwork such that inset for sf plots throws an error.  Workaround suggested on SO shown below:
# https://stackoverflow.com/questions/65208689/how-to-embed-a-map-using-the-inset-element-function-from-the-patchwork-package/65209110#65209110

plot_patch <- plot_text + 
  inset_element(plot_world, left = .1, right = .9, bottom = .48, top = .72)

plot_patch$patches$layout$widths  <- 1
plot_patch$patches$layout$heights <- 1

plot_patch + plot_phones + plot_layout(widths = c(.5, .5)) + 
  plot_annotation(
    theme = theme(plot.background = element_rect(fill = "#F2DFCE", color = NA)
    )
  )

path <- here::here("plots", 
                   glue::glue(tidy_year, "_", tidy_week, ".png"))

ggsave(path, width = 20, height = 20)

```

Didn't end up using below function
```{r junk pile}

# top <- function(dataset, col_name, col_name_2) {
# col_name <- enquo(col_name)
# col_name_2 <- enquo(col_name_2)
#  top_growth <- dataset %>% slice_max(!!col_name, n = 10)
# }

```

