---
title: "2020/44 Wind Turbines Canada"
author: "Bill Schmid"
date: "11/18/2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(tidytuesdayR)
library(showtext)
library(sf)
library(rnaturalearth)
library(colorspace)
library(gganimate)
library(cowplot)

tidy_year <- 2020
tidy_week <- 44

tuesdata <- tt_load(tidy_year,week=tidy_week)

df_orig_wind_turbines <- tuesdata$'wind-turbine'
```


```{r}
df_ontario_wind_turbines <- df_orig_wind_turbines %>% 
  filter(province_territory=="Ontario") %>% 
  mutate(commission_year = parse_number(commissioning_date)) %>% 
  arrange(commission_year) %>% 
  filter(commission_year>2005)

sf_ontario <- ne_states("Canada", returnclass = "sf") %>% 
  filter(name == "Ontario")

ont_bbox_2 <- c(-85, 41.7, -74.3, 48)

font_add_google(name="BioRhyme",family="BioRhyme")
showtext_auto()
```

Static Plot
```{r}
plot_static_wind_turbine <- ggplot()+
  geom_sf(data = sf_ontario, inherit.aes = FALSE, color = darken("#2F394D"), fill = "#F2EFEA") +
  geom_hex(data=df_ontario_wind_turbines,aes(x=longitude,y=latitude),alpha=.8)+
  coord_sf(xlim = c(-85,-74.3),
           ylim=c(41.7,48))+
  scale_fill_viridis_c(option="C")+
  theme_void()+
  labs(title="Wind Turbines Built (2006-2019)",
    caption = "Visualization: Bill Schmid @schmid_07 | Source: Government of Canada")+
  theme(plot.margin = margin(15,0,0,15),
        plot.background = element_rect("#999999"),
        legend.direction ="horizontal",
        legend.position = c(.75,.25),
        legend.key.size = unit(1.2,"cm"),
        legend.text = element_text(size=20,face="bold"),
        plot.caption = element_text(size=15,family = "BioRhyme"),
        plot.title = element_text(size=35,family = "BioRhyme",
                                  hjust=.5,margin = margin(t=10,b=25)),
        legend.title = element_text(size=20,family="BioRhyme",face="bold"))+
  guides(fill = guide_colourbar(title.position="top",
                                title=NULL))+
  draw_label("Southern \n Ontario",
             size=35,
             fontfamily = "BioRhyme",
             x=-77,y=47.5)
```

Animation
```{r}
plot_gif_wind_turbine <- ggplot()+
  geom_sf(data = sf_ontario, inherit.aes = FALSE, color = darken("#2F394D"), fill = "#F2EFEA") +
  geom_hex(data=df_ontario_wind_turbines,aes(x=longitude,y=latitude),alpha=.8)+
  coord_sf(xlim = c(-85,-74.3),
           ylim=c(41.7,48))+
  scale_fill_viridis_c(option="C")+
  theme_void()+
  labs(caption = "Visualization: Bill Schmid @schmid_07 | Source: Government of Canada")+
  theme(plot.margin = margin(15,0,0,15),
        plot.background = element_rect("#999999"),
        legend.direction ="horizontal",
        legend.position = c(.75,.25),
        legend.key.size = unit(.8,"cm"),
        legend.text = element_text(size=15,face="bold"),
        plot.caption = element_text(size=12),
        legend.title = element_text(size=15,face="bold"))+
  guides(fill = guide_colourbar(title.position="top",
                                title="Wind Turbines"))+
  draw_label("Southern \n Ontario",
             size=30,
             x=-77,y=47.5)

b <- plot_gif_wind_turbine +
  transition_manual(frames=factor(df_ontario_wind_turbines$commission_year,
                                  levels = unique(commission_year)),
                    cumulative = FALSE)+
  labs(title = "Year: {current_frame}")+
  theme(plot.title = element_text(hjust=.5,
                                  size=20,
                                  margin = margin(b=10)))

animate(plot = b,nframes=length(unique(df_ontario_wind_turbines$commission_year)),
        fps = .5)


anim_save("Ontario_Wind_Turbines.gif")

ggsave(plot= plot_static_wind_turbine,"Ontario_Wind_Turbines.png",width = 18, height = 10)
```
